# Generated by Django 4.0.6 on 2022-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
