# Generated by Django 4.0.6 on 2022-07-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_topic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=55)),
                ('count', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.topic')),
            ],
        ),
    ]
