# Generated by Django 4.0.6 on 2022-07-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='option_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together={('id', 'topic', 'option_no')},
        ),
    ]
