# Generated by Django 4.0.6 on 2022-07-23 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reactions',
            new_name='Reaction',
        ),
    ]
