# Generated by Django 4.0.6 on 2022-07-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_rename_reactions_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reaction',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.topic'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'choice', 'topic')},
        ),
    ]
