# Generated by Django 4.0.6 on 2022-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_reaction_unique_together_reaction_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='wide_image',
            field=models.URLField(default=None),
        ),
    ]
